public class try_catch_2 {
    public static void main(String[] args) {
        int a=1000/0;
System.out.println("The division done Result is: " + a);
//       }
//       try{
//           int a=1000/0;
//           System.out.println("The division done Result is: " + a);
//       }
//       catch (Exception a){
//           System.out.println("Failed to divide Reason: ");
//           System.out.println(a);
//       }

    }
}
